// THIS IS AN AUTOMATICALLY GENERATED FILE.
// DO NOT MODIFY BY HAND!!
//
// Generated by zcm-gen

#include <string.h>
#ifndef ZCM_EMBEDDED
#include <stdio.h>
#endif
#include "SCU_CAN_STS.h"

static int __SCU_CAN_STS_hash_computed = 0;
static uint64_t __SCU_CAN_STS_hash;

uint64_t __SCU_CAN_STS_hash_recursive(const __zcm_hash_ptr* p)
{
    const __zcm_hash_ptr* fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __SCU_CAN_STS_get_hash)
            return 0;

    __zcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__SCU_CAN_STS_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x7016131faf764e2eLL
         + __int8_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __SCU_CAN_STS_get_hash(void)
{
    if (!__SCU_CAN_STS_hash_computed) {
        __SCU_CAN_STS_hash = (int64_t)__SCU_CAN_STS_hash_recursive(NULL);
        __SCU_CAN_STS_hash_computed = 1;
    }

    return __SCU_CAN_STS_hash;
}

int __SCU_CAN_STS_encode_array(void* buf, uint32_t offset, uint32_t maxlen, const SCU_CAN_STS* p, uint32_t elements)
{
    uint32_t pos_byte = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        /* LngCtrlMode */
        thislen = __int8_t_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].LngCtrlMode), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* LngAutoCheckReport */
        thislen = __int32_t_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].LngAutoCheckReport), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* LngQuitReport */
        thislen = __int32_t_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].LngQuitReport), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* GearLeverIntv */
        thislen = __int8_t_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].GearLeverIntv), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* BrkPedalSt */
        thislen = __int8_t_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].BrkPedalSt), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* ActVehWheelTorq */
        thislen = __int16_t_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].ActVehWheelTorq), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* VehWheelTorqMax */
        thislen = __int16_t_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].VehWheelTorqMax), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* GasPedalAcPst */
        thislen = __float_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].GasPedalAcPst), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* AccElecECFail */
        thislen = __int8_t_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].AccElecECFail), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* VehRdySt */
        thislen = __int8_t_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].VehRdySt), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* VehDrvMod */
        thislen = __int8_t_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].VehDrvMod), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* VehRng */
        thislen = __int8_t_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].VehRng), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* CrntGearLvl */
        thislen = __int8_t_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].CrntGearLvl), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* VehSpd */
        thislen = __float_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].VehSpd), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* ABSActiveSt */
        thislen = __int8_t_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].ABSActiveSt), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* CDDAvailable */
        thislen = __int8_t_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].CDDAvailable), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* AEBAvailable */
        thislen = __int8_t_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].AEBAvailable), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* CDDFail */
        thislen = __int8_t_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].CDDFail), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* CDDActive */
        thislen = __int8_t_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].CDDActive), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* AEBActive */
        thislen = __int8_t_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].AEBActive), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* VehicleStandStillSt */
        thislen = __int8_t_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].VehicleStandStillSt), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* ActVehLongAccel */
        thislen = __float_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].ActVehLongAccel), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* VehLongAccelOffset */
        thislen = __float_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].VehLongAccelOffset), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* SysSt */
        thislen = __int8_t_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].SysSt), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* SwitchSt */
        thislen = __int8_t_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].SwitchSt), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* FailSt */
        thislen = __int8_t_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].FailSt), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* LatCtrlMode */
        thislen = __int8_t_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].LatCtrlMode), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* LatAutoCheckReport */
        thislen = __int32_t_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].LatAutoCheckReport), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* LatQuitReport */
        thislen = __int32_t_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].LatQuitReport), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* StrngWhlIntv */
        thislen = __int8_t_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].StrngWhlIntv), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* SteeringAngle */
        thislen = __float_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].SteeringAngle), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* SteeringAngleVD */
        thislen = __int8_t_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].SteeringAngleVD), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* SteeringAngleSpd */
        thislen = __int8_t_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].SteeringAngleSpd), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* SteeringAngleSpdVD */
        thislen = __int8_t_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].SteeringAngleSpdVD), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* StrngWhlTorq */
        thislen = __float_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].StrngWhlTorq), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* StrngWhlTorqVD */
        thislen = __int8_t_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].StrngWhlTorqVD), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* WarnLamp */
        thislen = __int8_t_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].WarnLamp), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* ActVeLaltrlAccel */
        thislen = __float_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].ActVeLaltrlAccel), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* VehLaltrlAccelOffset */
        thislen = __float_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].VehLaltrlAccelOffset), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* YawRate */
        thislen = __float_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].YawRate), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* YawRateOffset */
        thislen = __float_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].YawRateOffset), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

    }
    return pos_byte;
}

int SCU_CAN_STS_encode(void* buf, uint32_t offset, uint32_t maxlen, const SCU_CAN_STS* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __SCU_CAN_STS_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __SCU_CAN_STS_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t __SCU_CAN_STS_encoded_array_size(const SCU_CAN_STS* p, uint32_t elements)
{
    uint32_t size = 0, element;
    for (element = 0; element < elements; ++element) {

        size += __int8_t_encoded_array_size(&(p[element].LngCtrlMode), 1); // LngCtrlMode

        size += __int32_t_encoded_array_size(&(p[element].LngAutoCheckReport), 1); // LngAutoCheckReport

        size += __int32_t_encoded_array_size(&(p[element].LngQuitReport), 1); // LngQuitReport

        size += __int8_t_encoded_array_size(&(p[element].GearLeverIntv), 1); // GearLeverIntv

        size += __int8_t_encoded_array_size(&(p[element].BrkPedalSt), 1); // BrkPedalSt

        size += __int16_t_encoded_array_size(&(p[element].ActVehWheelTorq), 1); // ActVehWheelTorq

        size += __int16_t_encoded_array_size(&(p[element].VehWheelTorqMax), 1); // VehWheelTorqMax

        size += __float_encoded_array_size(&(p[element].GasPedalAcPst), 1); // GasPedalAcPst

        size += __int8_t_encoded_array_size(&(p[element].AccElecECFail), 1); // AccElecECFail

        size += __int8_t_encoded_array_size(&(p[element].VehRdySt), 1); // VehRdySt

        size += __int8_t_encoded_array_size(&(p[element].VehDrvMod), 1); // VehDrvMod

        size += __int8_t_encoded_array_size(&(p[element].VehRng), 1); // VehRng

        size += __int8_t_encoded_array_size(&(p[element].CrntGearLvl), 1); // CrntGearLvl

        size += __float_encoded_array_size(&(p[element].VehSpd), 1); // VehSpd

        size += __int8_t_encoded_array_size(&(p[element].ABSActiveSt), 1); // ABSActiveSt

        size += __int8_t_encoded_array_size(&(p[element].CDDAvailable), 1); // CDDAvailable

        size += __int8_t_encoded_array_size(&(p[element].AEBAvailable), 1); // AEBAvailable

        size += __int8_t_encoded_array_size(&(p[element].CDDFail), 1); // CDDFail

        size += __int8_t_encoded_array_size(&(p[element].CDDActive), 1); // CDDActive

        size += __int8_t_encoded_array_size(&(p[element].AEBActive), 1); // AEBActive

        size += __int8_t_encoded_array_size(&(p[element].VehicleStandStillSt), 1); // VehicleStandStillSt

        size += __float_encoded_array_size(&(p[element].ActVehLongAccel), 1); // ActVehLongAccel

        size += __float_encoded_array_size(&(p[element].VehLongAccelOffset), 1); // VehLongAccelOffset

        size += __int8_t_encoded_array_size(&(p[element].SysSt), 1); // SysSt

        size += __int8_t_encoded_array_size(&(p[element].SwitchSt), 1); // SwitchSt

        size += __int8_t_encoded_array_size(&(p[element].FailSt), 1); // FailSt

        size += __int8_t_encoded_array_size(&(p[element].LatCtrlMode), 1); // LatCtrlMode

        size += __int32_t_encoded_array_size(&(p[element].LatAutoCheckReport), 1); // LatAutoCheckReport

        size += __int32_t_encoded_array_size(&(p[element].LatQuitReport), 1); // LatQuitReport

        size += __int8_t_encoded_array_size(&(p[element].StrngWhlIntv), 1); // StrngWhlIntv

        size += __float_encoded_array_size(&(p[element].SteeringAngle), 1); // SteeringAngle

        size += __int8_t_encoded_array_size(&(p[element].SteeringAngleVD), 1); // SteeringAngleVD

        size += __int8_t_encoded_array_size(&(p[element].SteeringAngleSpd), 1); // SteeringAngleSpd

        size += __int8_t_encoded_array_size(&(p[element].SteeringAngleSpdVD), 1); // SteeringAngleSpdVD

        size += __float_encoded_array_size(&(p[element].StrngWhlTorq), 1); // StrngWhlTorq

        size += __int8_t_encoded_array_size(&(p[element].StrngWhlTorqVD), 1); // StrngWhlTorqVD

        size += __int8_t_encoded_array_size(&(p[element].WarnLamp), 1); // WarnLamp

        size += __float_encoded_array_size(&(p[element].ActVeLaltrlAccel), 1); // ActVeLaltrlAccel

        size += __float_encoded_array_size(&(p[element].VehLaltrlAccelOffset), 1); // VehLaltrlAccelOffset

        size += __float_encoded_array_size(&(p[element].YawRate), 1); // YawRate

        size += __float_encoded_array_size(&(p[element].YawRateOffset), 1); // YawRateOffset

    }
    return size;
}

uint32_t SCU_CAN_STS_encoded_size(const SCU_CAN_STS* p)
{
    return 8 + __SCU_CAN_STS_encoded_array_size(p, 1);
}

int __SCU_CAN_STS_decode_array(const void* buf, uint32_t offset, uint32_t maxlen, SCU_CAN_STS* p, uint32_t elements)
{
    uint32_t pos_byte = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        /* LngCtrlMode */
        thislen = __int8_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].LngCtrlMode), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* LngAutoCheckReport */
        thislen = __int32_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].LngAutoCheckReport), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* LngQuitReport */
        thislen = __int32_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].LngQuitReport), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* GearLeverIntv */
        thislen = __int8_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].GearLeverIntv), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* BrkPedalSt */
        thislen = __int8_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].BrkPedalSt), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* ActVehWheelTorq */
        thislen = __int16_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].ActVehWheelTorq), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* VehWheelTorqMax */
        thislen = __int16_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].VehWheelTorqMax), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* GasPedalAcPst */
        thislen = __float_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].GasPedalAcPst), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* AccElecECFail */
        thislen = __int8_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].AccElecECFail), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* VehRdySt */
        thislen = __int8_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].VehRdySt), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* VehDrvMod */
        thislen = __int8_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].VehDrvMod), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* VehRng */
        thislen = __int8_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].VehRng), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* CrntGearLvl */
        thislen = __int8_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].CrntGearLvl), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* VehSpd */
        thislen = __float_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].VehSpd), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* ABSActiveSt */
        thislen = __int8_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].ABSActiveSt), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* CDDAvailable */
        thislen = __int8_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].CDDAvailable), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* AEBAvailable */
        thislen = __int8_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].AEBAvailable), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* CDDFail */
        thislen = __int8_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].CDDFail), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* CDDActive */
        thislen = __int8_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].CDDActive), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* AEBActive */
        thislen = __int8_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].AEBActive), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* VehicleStandStillSt */
        thislen = __int8_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].VehicleStandStillSt), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* ActVehLongAccel */
        thislen = __float_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].ActVehLongAccel), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* VehLongAccelOffset */
        thislen = __float_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].VehLongAccelOffset), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* SysSt */
        thislen = __int8_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].SysSt), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* SwitchSt */
        thislen = __int8_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].SwitchSt), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* FailSt */
        thislen = __int8_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].FailSt), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* LatCtrlMode */
        thislen = __int8_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].LatCtrlMode), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* LatAutoCheckReport */
        thislen = __int32_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].LatAutoCheckReport), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* LatQuitReport */
        thislen = __int32_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].LatQuitReport), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* StrngWhlIntv */
        thislen = __int8_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].StrngWhlIntv), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* SteeringAngle */
        thislen = __float_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].SteeringAngle), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* SteeringAngleVD */
        thislen = __int8_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].SteeringAngleVD), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* SteeringAngleSpd */
        thislen = __int8_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].SteeringAngleSpd), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* SteeringAngleSpdVD */
        thislen = __int8_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].SteeringAngleSpdVD), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* StrngWhlTorq */
        thislen = __float_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].StrngWhlTorq), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* StrngWhlTorqVD */
        thislen = __int8_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].StrngWhlTorqVD), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* WarnLamp */
        thislen = __int8_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].WarnLamp), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* ActVeLaltrlAccel */
        thislen = __float_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].ActVeLaltrlAccel), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* VehLaltrlAccelOffset */
        thislen = __float_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].VehLaltrlAccelOffset), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* YawRate */
        thislen = __float_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].YawRate), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* YawRateOffset */
        thislen = __float_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].YawRateOffset), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

    }
    return pos_byte;
}

int __SCU_CAN_STS_decode_array_cleanup(SCU_CAN_STS* p, uint32_t elements)
{
    uint32_t element;
    for (element = 0; element < elements; ++element) {

        __int8_t_decode_array_cleanup(&(p[element].LngCtrlMode), 1);

        __int32_t_decode_array_cleanup(&(p[element].LngAutoCheckReport), 1);

        __int32_t_decode_array_cleanup(&(p[element].LngQuitReport), 1);

        __int8_t_decode_array_cleanup(&(p[element].GearLeverIntv), 1);

        __int8_t_decode_array_cleanup(&(p[element].BrkPedalSt), 1);

        __int16_t_decode_array_cleanup(&(p[element].ActVehWheelTorq), 1);

        __int16_t_decode_array_cleanup(&(p[element].VehWheelTorqMax), 1);

        __float_decode_array_cleanup(&(p[element].GasPedalAcPst), 1);

        __int8_t_decode_array_cleanup(&(p[element].AccElecECFail), 1);

        __int8_t_decode_array_cleanup(&(p[element].VehRdySt), 1);

        __int8_t_decode_array_cleanup(&(p[element].VehDrvMod), 1);

        __int8_t_decode_array_cleanup(&(p[element].VehRng), 1);

        __int8_t_decode_array_cleanup(&(p[element].CrntGearLvl), 1);

        __float_decode_array_cleanup(&(p[element].VehSpd), 1);

        __int8_t_decode_array_cleanup(&(p[element].ABSActiveSt), 1);

        __int8_t_decode_array_cleanup(&(p[element].CDDAvailable), 1);

        __int8_t_decode_array_cleanup(&(p[element].AEBAvailable), 1);

        __int8_t_decode_array_cleanup(&(p[element].CDDFail), 1);

        __int8_t_decode_array_cleanup(&(p[element].CDDActive), 1);

        __int8_t_decode_array_cleanup(&(p[element].AEBActive), 1);

        __int8_t_decode_array_cleanup(&(p[element].VehicleStandStillSt), 1);

        __float_decode_array_cleanup(&(p[element].ActVehLongAccel), 1);

        __float_decode_array_cleanup(&(p[element].VehLongAccelOffset), 1);

        __int8_t_decode_array_cleanup(&(p[element].SysSt), 1);

        __int8_t_decode_array_cleanup(&(p[element].SwitchSt), 1);

        __int8_t_decode_array_cleanup(&(p[element].FailSt), 1);

        __int8_t_decode_array_cleanup(&(p[element].LatCtrlMode), 1);

        __int32_t_decode_array_cleanup(&(p[element].LatAutoCheckReport), 1);

        __int32_t_decode_array_cleanup(&(p[element].LatQuitReport), 1);

        __int8_t_decode_array_cleanup(&(p[element].StrngWhlIntv), 1);

        __float_decode_array_cleanup(&(p[element].SteeringAngle), 1);

        __int8_t_decode_array_cleanup(&(p[element].SteeringAngleVD), 1);

        __int8_t_decode_array_cleanup(&(p[element].SteeringAngleSpd), 1);

        __int8_t_decode_array_cleanup(&(p[element].SteeringAngleSpdVD), 1);

        __float_decode_array_cleanup(&(p[element].StrngWhlTorq), 1);

        __int8_t_decode_array_cleanup(&(p[element].StrngWhlTorqVD), 1);

        __int8_t_decode_array_cleanup(&(p[element].WarnLamp), 1);

        __float_decode_array_cleanup(&(p[element].ActVeLaltrlAccel), 1);

        __float_decode_array_cleanup(&(p[element].VehLaltrlAccelOffset), 1);

        __float_decode_array_cleanup(&(p[element].YawRate), 1);

        __float_decode_array_cleanup(&(p[element].YawRateOffset), 1);

    }
    return 0;
}

int SCU_CAN_STS_decode(const void* buf, uint32_t offset, uint32_t maxlen, SCU_CAN_STS* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __SCU_CAN_STS_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __SCU_CAN_STS_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int SCU_CAN_STS_decode_cleanup(SCU_CAN_STS* p)
{
    return __SCU_CAN_STS_decode_array_cleanup(p, 1);
}

uint32_t __SCU_CAN_STS_clone_array(const SCU_CAN_STS* p, SCU_CAN_STS* q, uint32_t elements)
{
    uint32_t n = 0, element;
    for (element = 0; element < elements; ++element) {

        n += __int8_t_clone_array(&(p[element].LngCtrlMode), &(q[element].LngCtrlMode), 1);

        n += __int32_t_clone_array(&(p[element].LngAutoCheckReport), &(q[element].LngAutoCheckReport), 1);

        n += __int32_t_clone_array(&(p[element].LngQuitReport), &(q[element].LngQuitReport), 1);

        n += __int8_t_clone_array(&(p[element].GearLeverIntv), &(q[element].GearLeverIntv), 1);

        n += __int8_t_clone_array(&(p[element].BrkPedalSt), &(q[element].BrkPedalSt), 1);

        n += __int16_t_clone_array(&(p[element].ActVehWheelTorq), &(q[element].ActVehWheelTorq), 1);

        n += __int16_t_clone_array(&(p[element].VehWheelTorqMax), &(q[element].VehWheelTorqMax), 1);

        n += __float_clone_array(&(p[element].GasPedalAcPst), &(q[element].GasPedalAcPst), 1);

        n += __int8_t_clone_array(&(p[element].AccElecECFail), &(q[element].AccElecECFail), 1);

        n += __int8_t_clone_array(&(p[element].VehRdySt), &(q[element].VehRdySt), 1);

        n += __int8_t_clone_array(&(p[element].VehDrvMod), &(q[element].VehDrvMod), 1);

        n += __int8_t_clone_array(&(p[element].VehRng), &(q[element].VehRng), 1);

        n += __int8_t_clone_array(&(p[element].CrntGearLvl), &(q[element].CrntGearLvl), 1);

        n += __float_clone_array(&(p[element].VehSpd), &(q[element].VehSpd), 1);

        n += __int8_t_clone_array(&(p[element].ABSActiveSt), &(q[element].ABSActiveSt), 1);

        n += __int8_t_clone_array(&(p[element].CDDAvailable), &(q[element].CDDAvailable), 1);

        n += __int8_t_clone_array(&(p[element].AEBAvailable), &(q[element].AEBAvailable), 1);

        n += __int8_t_clone_array(&(p[element].CDDFail), &(q[element].CDDFail), 1);

        n += __int8_t_clone_array(&(p[element].CDDActive), &(q[element].CDDActive), 1);

        n += __int8_t_clone_array(&(p[element].AEBActive), &(q[element].AEBActive), 1);

        n += __int8_t_clone_array(&(p[element].VehicleStandStillSt), &(q[element].VehicleStandStillSt), 1);

        n += __float_clone_array(&(p[element].ActVehLongAccel), &(q[element].ActVehLongAccel), 1);

        n += __float_clone_array(&(p[element].VehLongAccelOffset), &(q[element].VehLongAccelOffset), 1);

        n += __int8_t_clone_array(&(p[element].SysSt), &(q[element].SysSt), 1);

        n += __int8_t_clone_array(&(p[element].SwitchSt), &(q[element].SwitchSt), 1);

        n += __int8_t_clone_array(&(p[element].FailSt), &(q[element].FailSt), 1);

        n += __int8_t_clone_array(&(p[element].LatCtrlMode), &(q[element].LatCtrlMode), 1);

        n += __int32_t_clone_array(&(p[element].LatAutoCheckReport), &(q[element].LatAutoCheckReport), 1);

        n += __int32_t_clone_array(&(p[element].LatQuitReport), &(q[element].LatQuitReport), 1);

        n += __int8_t_clone_array(&(p[element].StrngWhlIntv), &(q[element].StrngWhlIntv), 1);

        n += __float_clone_array(&(p[element].SteeringAngle), &(q[element].SteeringAngle), 1);

        n += __int8_t_clone_array(&(p[element].SteeringAngleVD), &(q[element].SteeringAngleVD), 1);

        n += __int8_t_clone_array(&(p[element].SteeringAngleSpd), &(q[element].SteeringAngleSpd), 1);

        n += __int8_t_clone_array(&(p[element].SteeringAngleSpdVD), &(q[element].SteeringAngleSpdVD), 1);

        n += __float_clone_array(&(p[element].StrngWhlTorq), &(q[element].StrngWhlTorq), 1);

        n += __int8_t_clone_array(&(p[element].StrngWhlTorqVD), &(q[element].StrngWhlTorqVD), 1);

        n += __int8_t_clone_array(&(p[element].WarnLamp), &(q[element].WarnLamp), 1);

        n += __float_clone_array(&(p[element].ActVeLaltrlAccel), &(q[element].ActVeLaltrlAccel), 1);

        n += __float_clone_array(&(p[element].VehLaltrlAccelOffset), &(q[element].VehLaltrlAccelOffset), 1);

        n += __float_clone_array(&(p[element].YawRate), &(q[element].YawRate), 1);

        n += __float_clone_array(&(p[element].YawRateOffset), &(q[element].YawRateOffset), 1);

    }
    return n;
}

SCU_CAN_STS* SCU_CAN_STS_copy(const SCU_CAN_STS* p)
{
    SCU_CAN_STS* q = (SCU_CAN_STS*) malloc(sizeof(SCU_CAN_STS));
    __SCU_CAN_STS_clone_array(p, q, 1);
    return q;
}

void SCU_CAN_STS_destroy(SCU_CAN_STS* p)
{
    __SCU_CAN_STS_decode_array_cleanup(p, 1);
    free(p);
}

int SCU_CAN_STS_publish(zcm_t* zcm, const char* channel, const SCU_CAN_STS* p)
{
      uint32_t max_data_size = SCU_CAN_STS_encoded_size (p);
      uint8_t* buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = SCU_CAN_STS_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = zcm_publish (zcm, channel, buf, (uint32_t)data_size);
      free (buf);
      return status;
}

struct _SCU_CAN_STS_subscription_t {
    SCU_CAN_STS_handler_t user_handler;
    void* userdata;
    zcm_sub_t* z_sub;
};
static
void SCU_CAN_STS_handler_stub (const zcm_recv_buf_t* rbuf,
                            const char* channel, void* userdata)
{
    int status;
    SCU_CAN_STS p;
    memset(&p, 0, sizeof(SCU_CAN_STS));
    status = SCU_CAN_STS_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        #ifndef ZCM_EMBEDDED
        fprintf (stderr, "error %d decoding SCU_CAN_STS!!!\n", status);
        #endif
        return;
    }

    SCU_CAN_STS_subscription_t* h = (SCU_CAN_STS_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    SCU_CAN_STS_decode_cleanup (&p);
}

SCU_CAN_STS_subscription_t* SCU_CAN_STS_subscribe (zcm_t* zcm,
                    const char* channel,
                    SCU_CAN_STS_handler_t f, void* userdata)
{
    SCU_CAN_STS_subscription_t* n = (SCU_CAN_STS_subscription_t*)
                       malloc(sizeof(SCU_CAN_STS_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->z_sub = zcm_subscribe (zcm, channel,
                              SCU_CAN_STS_handler_stub, n);
    if (n->z_sub == NULL) {
        #ifndef ZCM_EMBEDDED
        fprintf (stderr,"couldn't reg SCU_CAN_STS ZCM handler!\n");
        #endif
        free (n);
        return NULL;
    }
    return n;
}

int SCU_CAN_STS_unsubscribe(zcm_t* zcm, SCU_CAN_STS_subscription_t* hid)
{
    int status = zcm_unsubscribe (zcm, hid->z_sub);
    if (0 != status) {
        #ifndef ZCM_EMBEDDED
        fprintf(stderr,
           "couldn't unsubscribe SCU_CAN_STS_handler %p!\n", hid);
        #endif
        return -1;
    }
    free (hid);
    return 0;
}

